apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "formal-cloud-admission.fullname" . }}-caddy
  labels:
    {{- include "formal-cloud-admission.labels" . | nindent 4 }}
data:
  Caddyfile: |
    :{{ .Values.service.targetPort }} {
      tls /tls/tls.crt /tls/tls.key
      reverse_proxy 127.0.0.1:8080
    }
