{{- if .Values.tls.certManager.enabled }}
{{- if .Values.tls.certManager.createIssuer }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ .Values.tls.certManager.issuerRef.name }}
  labels:
    {{- include "formal-cloud-admission.labels" . | nindent 4 }}
spec:
  selfSigned: {}
---
{{- end }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.tls.certManager.certificateName }}
  labels:
    {{- include "formal-cloud-admission.labels" . | nindent 4 }}
spec:
  secretName: {{ .Values.tls.certManager.secretName }}
  dnsNames:
    - {{ include "formal-cloud-admission.fullname" . }}
    - {{ include "formal-cloud-admission.fullname" . }}.{{ .Release.Namespace }}
    - {{ include "formal-cloud-admission.fullname" . }}.{{ .Release.Namespace }}.svc
    - {{ include "formal-cloud-admission.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    name: {{ .Values.tls.certManager.issuerRef.name }}
    kind: {{ .Values.tls.certManager.issuerRef.kind }}
    group: {{ .Values.tls.certManager.issuerRef.group }}
{{- end }}
