apiVersion: v1
kind: Service
metadata:
  name: {{ include "formal-cloud-admission.fullname" . }}
  labels:
    {{- include "formal-cloud-admission.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "formal-cloud-admission.selectorLabels" . | nindent 4 }}
  ports:
    - name: https
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
