{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "formal-cloud-admission.serviceAccountName" . }}
  labels:
    {{- include "formal-cloud-admission.labels" . | nindent 4 }}
{{- end }}
